name: Tests
on: 
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install packratparsergenerator[test]
      - name: Test with pytest
        run: |
          coverage run --branch -m pytest 
          coverage report -m --omit=tests/* --skip-empty
          coverage xml --skip-empty --omit=tests/* -o reports/coverage/coverage.xml
          genbadge coverage
      #- uses: stefanzweifel/git-auto-commit-action@v4 # Commits any changes in this case commits the xml coverage file
      #  with:
      #    commit_message: Commit coverage file to repo

  